name: my-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - run: make install
      - name: Test eslint
        run: make lint
      - name: Test jest
        run: make test
      - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ce7a4a525c5c5477c7dcfbb607348671e6b7f2b53d9caf337c708b66697a7e44
      with:
        coverageCommand: npx jest --coverage